name: my_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  go_router: ^12.1.3
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.1.3
  path_provider: ^2.1.1
  http: ^0.13.0
  flutter_easyloading: ^3.0.5
  easy_localization: ^3.0.3
  rxdart: ^0.27.7
  gradient_coloured_buttons: ^0.1.0
  fl_country_code_picker: ^0.1.9+1
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  font_awesome_flutter: ^10.6.0
  lottie: ^2.6.0
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  dotted_line: ^3.2.2
  overlay_tooltip: ^0.2.3
  flutter_rating_bar: ^4.0.1
  ticket_material: ^0.3.1
  ticket_widget: ^1.0.2
  calendar_date_picker2: ^0.5.3
  intl: ^0.18.1
  flutter_staggered_animations: ^1.1.1
  url_launcher: ^6.2.4
  collection: ^1.18.0
  flutter_multi_formatter: ^2.12.4
  # Firebase
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  cloud_firestore: ^4.13.1
  firebase_storage: ^11.6.0
  flutter_flavorizr: ^2.2.1

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_dotenv: ^5.1.0
  change_app_package_name: ^1.1.0
  build_runner: ^2.4.6
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500

# dart run flutter_flavorizr -p android:buildGradle,android:androidManifest,google:firebase
flavorizr:
  flavors:
    dev:
      app:
        name: "(Dev) Travo"
      android:
        applicationId: "com.aci.travoapp.dev"
        firebase:
          config: ".firebase/dev/google-services.json"
    prod:
      app:
        name: "Travo"
      android:
        applicationId: "com.aci.travoapp"
        firebase:
          config: ".firebase/prod/google-services.json"